module.exports=[
'./gulp/task/pug',
'./gulp/task/sass',
'./gulp/task/scripts',
'./gulp/task/serve',
'./gulp/task/watch',
'./gulp/task/img',
'./gulp/task/svg',
'./gulp/task/fonts',
'./gulp/task/clean',
'./gulp/task/img'
];